/**
 * Static & Reconciled compound location data with GPS verification markers.
 * Safe to import in Server Components and SSR pages.
 */

export interface CompoundLocation {
  code: string;
  nameEn: string;
  nameAr: string;
  developer: string;
  lat: number;
  lng: number;
  unitsCount: number;
  isGpsVerified: boolean;
  notes?: string;
}

export const NEW_CAIRO_COMPOUNDS: CompoundLocation[] = [
  {
    code: 'HP',
    nameEn: 'Hyde Park',
    nameAr: 'هايد بارك',
    developer: 'Hyde Park Developments',
    lat: 30.008,
    lng: 31.645,
    unitsCount: 38,
    isGpsVerified: true,
  },
  {
    code: 'MVI',
    nameEn: 'Mountain View iCity',
    nameAr: 'ماونتن فيو أيكتي',
    developer: 'Mountain View',
    lat: 30.014,
    lng: 31.618,
    unitsCount: 24,
    isGpsVerified: true,
  },
  {
    code: 'MIV',
    nameEn: 'Mivida',
    nameAr: 'ميفيدا',
    developer: 'Emaar Misr',
    lat: 30.007,
    lng: 31.589,
    unitsCount: 42,
    isGpsVerified: true,
  },
  {
    code: 'MT',
    nameEn: 'Madinaty',
    nameAr: 'مدينتي',
    developer: 'TMG',
    lat: 30.0984,
    lng: 31.6288,
    unitsCount: 68,
    isGpsVerified: true,
  },
  {
    code: 'RH',
    nameEn: 'Al Rehab',
    nameAr: 'الرحاب',
    developer: 'TMG',
    lat: 30.0608,
    lng: 31.4936,
    unitsCount: 54,
    isGpsVerified: true,
  },
  {
    code: 'UTC',
    nameEn: 'Up Town Cairo',
    nameAr: 'أب تاون كايرو',
    developer: 'Emaar Misr',
    lat: 30.0189,
    lng: 31.3094,
    unitsCount: 29,
    isGpsVerified: true,
  },
  {
    code: 'CFC',
    nameEn: 'Cairo Festival City (CFC)',
    nameAr: 'كايرو فيستيفال سيتي',
    developer: 'Al Futtaim',
    lat: 30.0275,
    lng: 31.4089,
    unitsCount: 26,
    isGpsVerified: true,
  },
  {
    code: 'EST',
    nameEn: 'Eastown (SODIC)',
    nameAr: 'إيستاون',
    developer: 'SODIC',
    lat: 30.0195,
    lng: 31.4985,
    unitsCount: 25,
    isGpsVerified: true,
  },
  {
    code: 'VLT',
    nameEn: 'Villette (SODIC)',
    nameAr: 'فيليت',
    developer: 'SODIC',
    lat: 30.0125,
    lng: 31.5312,
    unitsCount: 22,
    isGpsVerified: true,
  },
  {
    code: 'PH',
    nameEn: 'Palm Hills New Cairo',
    nameAr: 'بالم هيلز',
    developer: 'Palm Hills Developments',
    lat: 30.0118,
    lng: 31.5188,
    unitsCount: 31,
    isGpsVerified: true,
  },
  {
    code: 'SL',
    nameEn: 'Swan Lake Residence',
    nameAr: 'سوان ليك',
    developer: 'Hassan Allam',
    lat: 30.0521,
    lng: 31.4682,
    unitsCount: 19,
    isGpsVerified: true,
  },
  {
    code: 'FS',
    nameEn: 'Fifth Square',
    nameAr: 'فيفت سكوير',
    developer: 'Al Marasem',
    lat: 30.0412,
    lng: 31.5123,
    unitsCount: 18,
    isGpsVerified: true,
  },
  {
    code: 'TAJ',
    nameEn: 'Taj City',
    nameAr: 'تاج سيتي',
    developer: 'Madinet Masr (MNHD)',
    lat: 30.065,
    lng: 31.531,
    unitsCount: 17,
    isGpsVerified: true,
  },
  {
    code: 'LV',
    nameEn: 'Lake View Residence',
    nameAr: 'ليك فيو',
    developer: 'El Hazek',
    lat: 30.0225,
    lng: 31.4812,
    unitsCount: 15,
    isGpsVerified: true,
  },
  {
    code: 'BD',
    nameEn: 'Badya (Palm Hills)',
    nameAr: 'بادية',
    developer: 'Palm Hills',
    lat: 29.9281,
    lng: 30.8711,
    unitsCount: 14,
    isGpsVerified: true,
  },
  {
    code: 'ZED',
    nameEn: 'Zed East',
    nameAr: 'زيد إيست',
    developer: 'Ora Developers',
    lat: 30.095,
    lng: 31.61,
    unitsCount: 12,
    isGpsVerified: true,
  },
  {
    code: 'KH',
    nameEn: 'Katameya Heights',
    nameAr: 'قطامية هايتس',
    developer: 'Katameya Group',
    lat: 29.99,
    lng: 31.48,
    unitsCount: 10,
    isGpsVerified: true,
  },
  // Pending Direction / Custom Drops needing coordinate review:
  {
    code: 'UNV-NC',
    nameEn: 'General New Cairo Area (Unspecified Sector)',
    nameAr: 'القاهرة الجديدة (قطاع غير محدد)',
    developer: 'Private / Multi-Developer',
    lat: 30.0263,
    lng: 31.4913,
    unitsCount: 24,
    isGpsVerified: false,
    notes: '📍 Location Pending Verification — Units listed without specific compound address (Marked for user review)',
  },
  {
    code: 'UNV-NRG',
    nameEn: 'El Narges & Choueifat Area',
    nameAr: 'النرجس والشويفات',
    developer: 'Private Owner Drops',
    lat: 30.0142,
    lng: 31.4421,
    unitsCount: 15,
    isGpsVerified: false,
    notes: '📍 Location Pending Verification — Private villa & floor drops needing exact street mapping',
  },
];
