/**
 * Static & Reconciled compound location data with GPS verification markers.
 * Safe to import in Server Components and SSR pages.
 */

export interface CompoundLocation {
  code: string;
  nameEn: string;
  nameAr: string;
  developer: string;
  lat: number;
  lng: number;
  unitsCount: number;
  isGpsVerified: boolean;
  notes?: string;
}

export const NEW_CAIRO_COMPOUNDS: CompoundLocation[] = [
  {
    code: 'HP',
    nameEn: 'Hyde Park',
    nameAr: 'هايد بارك',
    developer: 'Hyde Park Developments',
    lat: 30.008,
    lng: 31.645,
    unitsCount: 38,
    isGpsVerified: true,
  },
  {
    code: 'MVI',
    nameEn: 'Mountain View iCity',
    nameAr: 'ماونتن فيو أيكتي',
    developer: 'Mountain View',
    lat: 30.014,
    lng: 31.618,
    unitsCount: 24,
    isGpsVerified: true,
  },
  {
    code: 'MIV',
    nameEn: 'Mivida',
    nameAr: 'ميفيدا',
    developer: 'Emaar Misr',
    lat: 30.007,
    lng: 31.589,
    unitsCount: 42,
    isGpsVerified: true,
  },
  {
    code: 'MT',
    nameEn: 'Madinaty',
    nameAr: 'مدينتي',
    developer: 'TMG',
    lat: 30.0984,
    lng: 31.6288,
    unitsCount: 68,
    isGpsVerified: true,
  },
  {
    code: 'RH',
    nameEn: 'Al Rehab',
    nameAr: 'الرحاب',
    developer: 'TMG',
    lat: 30.0608,
    lng: 31.4936,
    unitsCount: 54,
    isGpsVerified: true,
  },
  {
    code: 'UTC',
    nameEn: 'Uptown Cairo',
    nameAr: 'أب تاون كايرو',
    developer: 'Emaar Misr',
    lat: 30.0189,
    lng: 31.3094,
    unitsCount: 29,
    isGpsVerified: true,
  },
  {
    code: 'CFC',
    nameEn: 'Cairo Festival City',
    nameAr: 'كايرو فيستيفال سيتي',
    developer: 'Al Futtaim',
    lat: 30.0275,
    lng: 31.4089,
    unitsCount: 26,
    isGpsVerified: true,
  },
  {
    code: 'EST',
    nameEn: 'Eastown',
    nameAr: 'إيستاون',
    developer: 'SODIC',
    lat: 30.0195,
    lng: 31.4985,
    unitsCount: 25,
    isGpsVerified: true,
  },
  {
    code: 'VLT',
    nameEn: 'Villette',
    nameAr: 'فيليت',
    developer: 'SODIC',
    lat: 30.0125,
    lng: 31.5312,
    unitsCount: 22,
    isGpsVerified: true,
  },
  {
    code: 'PH',
    nameEn: 'Palm Hills New Cairo',
    nameAr: 'بالم هيلز',
    developer: 'Palm Hills Developments',
    lat: 30.0118,
    lng: 31.5188,
    unitsCount: 31,
    isGpsVerified: true,
  },
  {
    code: 'SL',
    nameEn: 'Swan Lake Residence',
    nameAr: 'سوان ليك',
    developer: 'Hassan Allam',
    lat: 30.0521,
    lng: 31.4682,
    unitsCount: 19,
    isGpsVerified: true,
  },
  {
    code: 'FS',
    nameEn: 'Fifth Square',
    nameAr: 'فيفت سكوير',
    developer: 'Al Marasem',
    lat: 30.0412,
    lng: 31.5123,
    unitsCount: 18,
    isGpsVerified: true,
  },
  {
    code: 'TAJ',
    nameEn: 'Taj City',
    nameAr: 'تاج سيتي',
    developer: 'Madinet Masr (MNHD)',
    lat: 30.065,
    lng: 31.531,
    unitsCount: 17,
    isGpsVerified: true,
  },
  {
    code: 'LV',
    nameEn: 'Lake View Residence',
    nameAr: 'ليك فيو',
    developer: 'El Hazek',
    lat: 30.0225,
    lng: 31.4812,
    unitsCount: 15,
    isGpsVerified: true,
  },
  {
    code: 'BD',
    nameEn: 'Badya',
    nameAr: 'بادية',
    developer: 'Palm Hills',
    lat: 29.9281,
    lng: 30.8711,
    unitsCount: 14,
    isGpsVerified: true,
  },
  {
    code: 'ZED',
    nameEn: 'Zed East',
    nameAr: 'زيد إيست',
    developer: 'Ora Developers',
    lat: 30.095,
    lng: 31.61,
    unitsCount: 12,
    isGpsVerified: true,
  },
  {
    code: 'KH',
    nameEn: 'Katameya Heights',
    nameAr: 'قطامية هايتس',
    developer: 'Katameya Group',
    lat: 29.99,
    lng: 31.48,
    unitsCount: 10,
    isGpsVerified: true,
  },
  {
    code: 'TWW',
    nameEn: 'The Waterway',
    nameAr: 'ذا ووتر واي',
    developer: 'The Waterway Developments',
    lat: 30.028,
    lng: 31.612,
    unitsCount: 25,
    isGpsVerified: true,
  },
  {
    code: 'STR',
    nameEn: 'Stone Residence',
    nameAr: 'ستون ريزيدنس',
    developer: 'Rooya Group',
    lat: 30.028,
    lng: 31.557,
    unitsCount: 20,
    isGpsVerified: true,
  },
  {
    code: 'SQR',
    nameEn: 'The Square',
    nameAr: 'ذا سكوير',
    developer: 'Al Ahly Sabbour',
    lat: 30.033,
    lng: 31.542,
    unitsCount: 16,
    isGpsVerified: true,
  },
  {
    code: 'PAT',
    nameEn: 'El Patio Oro',
    nameAr: 'إل باتيو أورو',
    developer: 'La Vista',
    lat: 30.029,
    lng: 31.56,
    unitsCount: 15,
    isGpsVerified: true,
  },
  {
    code: 'AV90',
    nameEn: '90 Avenue',
    nameAr: '90 أفينيو',
    developer: 'Tabarak',
    lat: 30.028,
    lng: 31.572,
    unitsCount: 62,
    isGpsVerified: true,
  },
  {
    code: 'GLR',
    nameEn: 'Galleria Moon Valley',
    nameAr: 'جاليريا مون فالي',
    developer: 'Arabia Holding',
    lat: 30.02,
    lng: 31.55,
    unitsCount: 61,
    isGpsVerified: true,
  },
  {
    code: 'D5',
    nameEn: 'District 5',
    nameAr: 'ديستريكت 5',
    developer: 'Marakez',
    lat: 30.012,
    lng: 31.5,
    unitsCount: 18,
    isGpsVerified: true,
  },
  {
    code: 'SAR',
    nameEn: 'Sarai',
    nameAr: 'ساراي',
    developer: 'Madinet Masr (MNHD)',
    lat: 30.005,
    lng: 31.66,
    unitsCount: 22,
    isGpsVerified: true,
  },
  {
    code: 'BLM',
    nameEn: 'Bloomfields',
    nameAr: 'بلومفيلدز',
    developer: 'Tatweer Misr',
    lat: 30.06,
    lng: 31.67,
    unitsCount: 18,
    isGpsVerified: true,
  },
  {
    code: 'NRG',
    nameEn: 'Al Narges',
    nameAr: 'النرجس',
    developer: 'New Cairo Prime',
    lat: 30.052,
    lng: 31.47,
    unitsCount: 25,
    isGpsVerified: true,
  },
  {
    code: 'BNF',
    nameEn: 'Al Banafsaj',
    nameAr: 'البنفسج',
    developer: 'New Cairo Prime',
    lat: 30.045,
    lng: 31.485,
    unitsCount: 22,
    isGpsVerified: true,
  },
  {
    code: 'AND',
    nameEn: 'Al Andalus',
    nameAr: 'الأندلس',
    developer: 'New Cairo Prime',
    lat: 30.052,
    lng: 31.49,
    unitsCount: 20,
    isGpsVerified: true,
  },
  {
    code: 'SAC',
    nameEn: 'South Academy',
    nameAr: 'جنوب الأكاديمية',
    developer: 'New Cairo Prime',
    lat: 30.005,
    lng: 31.44,
    unitsCount: 15,
    isGpsVerified: true,
  },
  {
    code: 'N90',
    nameEn: 'North 90th',
    nameAr: 'التسعين الشمالي',
    developer: 'North 90th Corridor',
    lat: 30.03,
    lng: 31.47,
    unitsCount: 18,
    isGpsVerified: true,
  },
  {
    code: 'GRD',
    nameEn: 'Gardenia City',
    nameAr: 'جاردينيا سيتي',
    developer: 'Al Ahly Sabbour / Armed Forces',
    lat: 30.082,
    lng: 31.412,
    unitsCount: 16,
    isGpsVerified: true,
  },
  // Pending Direction / Custom Drops needing coordinate review:
  {
    code: 'UNV-NC',
    nameEn: 'General New Cairo Area (Unspecified Sector)',
    nameAr: 'القاهرة الجديدة (قطاع غير محدد)',
    developer: 'Private / Multi-Developer',
    lat: 30.0263,
    lng: 31.4913,
    unitsCount: 24,
    isGpsVerified: false,
    notes: '📍 Location Pending Verification — Units listed without specific compound address (Marked for user review)',
  },
  {
    code: 'UNV-NRG',
    nameEn: 'El Narges & Choueifat Area',
    nameAr: 'النرجس والشويفات',
    developer: 'Private Owner Drops',
    lat: 30.0142,
    lng: 31.4421,
    unitsCount: 15,
    isGpsVerified: false,
    notes: '📍 Location Pending Verification — Private villa & floor drops needing exact street mapping',
  },
];
