'use client';
import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Pause, Play, Sparkles } from 'lucide-react';
import type { CardListing } from './PropertyCard';
import { useSite } from '@/lib/site/SiteContext';
import { HZDATA } from '@/lib/site/data';
const ROTATION_MS = 5200;
export default function PropertyShowcaseVideo() {
  const { isAr } = useSite();
  const listings = useMemo(() => (HZDATA.listings as CardListing[]).slice(0, 5), []);
  const [active, setActive] = useState(0); const [playing, setPlaying] = useState(true); const [progress, setProgress] = useState(0);
  useEffect(() => { if (!playing) return undefined; const started = Date.now(); const timer = window.setInterval(() => { const value = Math.min((Date.now() - started) / ROTATION_MS, 1); setProgress(value); if (value >= 1) { setActive((current) => (current + 1) % listings.length); setProgress(0); } }, 80); return () => window.clearInterval(timer); }, [active, listings.length, playing]);
  const current = listings[active]; if (!current) return null;
  return <section className="showcase-video" aria-label={isAr ? 'جولة في العقارات المميزة' : 'Featured property showcase'}><div className="showcase-video__media">{listings.map((listing, index) => <img key={listing.id} className={index === active ? 'showcase-video__image is-active' : 'showcase-video__image'} src={listing.img} alt="" aria-hidden={index !== active} />)}<div className="showcase-video__wash" /><div className="showcase-video__topline"><span className="showcase-video__live"><span /> {isAr ? 'اختيارات حية' : 'Live selection'}</span><span>{String(active + 1).padStart(2, '0')} / {String(listings.length).padStart(2, '0')}</span></div><div className="showcase-video__copy"><p className="showcase-video__eyebrow"><Sparkles size={14} /> {isAr ? 'اختيارات من محرك Sierra' : 'Curated by Sierra intelligence'}</p><h3>{current.type} in {current.cmp}</h3><p>{current.zone} · {current.beds} {isAr ? 'غرف' : 'beds'} · {current.area} m²</p><div className="showcase-video__actions"><Link href={'/property/' + current.id} className="showcase-video__cta">{isAr ? 'شاهد العقار' : 'View property'} <ArrowRight size={16} /></Link><button type="button" className="showcase-video__control" onClick={() => setPlaying((value) => !value)} aria-label={playing ? 'Pause showcase' : 'Play showcase'}>{playing ? <Pause size={16} /> : <Play size={16} />}<span>{playing ? (isAr ? 'إيقاف' : 'Pause') : (isAr ? 'تشغيل' : 'Play')}</span></button></div></div><div className="showcase-video__meta"><span className="showcase-video__price">{HZDATA.price(current)}</span><span className="showcase-video__score">AI {current.ai.toFixed(1)}</span></div><div className="showcase-video__progress"><span style={{ width: (progress * 100) + '%' }} /></div></div><div className="showcase-video__dots" role="tablist" aria-label={isAr ? 'العقارات' : 'Properties'}>{listings.map((listing, index) => <button key={listing.id} type="button" role="tab" aria-selected={index === active} aria-label={(isAr ? 'عقار ' : 'Property ') + (index + 1)} className={index === active ? 'is-active' : undefined} onClick={() => { setActive(index); setProgress(0); }} />)}</div><style jsx>{
".showcase-video{overflow:hidden;border:1px solid rgba(197,151,58,.35);border-radius:24px;background:#071523;box-shadow:0 24px 70px rgba(5,18,31,.22)}.showcase-video__media{position:relative;min-height:470px;overflow:hidden}.showcase-video__image{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:0;transform:scale(1.06);transition:opacity 900ms ease,transform 6s ease}.showcase-video__image.is-active{opacity:1;transform:scale(1)}.showcase-video__wash{position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,12,22,.92),rgba(3,12,22,.35) 58%,rgba(3,12,22,.12)),linear-gradient(0deg,rgba(3,12,22,.72),transparent 45%)}.showcase-video__topline,.showcase-video__meta{position:absolute;left:28px;right:28px;display:flex;justify-content:space-between;color:rgba(255,255,255,.76);font:700 11px/1 var(--font-mono);letter-spacing:.13em;text-transform:uppercase}.showcase-video__topline{top:26px}.showcase-video__live{display:flex;align-items:center;gap:8px}.showcase-video__live span{width:7px;height:7px;border-radius:50%;background:#49d6a2;box-shadow:0 0 12px #49d6a2}.showcase-video__copy{position:absolute;left:7%;bottom:82px;max-width:560px;color:#fff}.showcase-video__eyebrow{display:flex;align-items:center;gap:7px;margin:0 0 14px;color:#e4b95b;font:700 11px/1 var(--font-mono);letter-spacing:.08em;text-transform:uppercase}.showcase-video__copy h3{margin:0 0 10px;font:600 clamp(30px,4vw,56px)/1.02 var(--font-display);letter-spacing:-.03em}.showcase-video__copy>p:not(.showcase-video__eyebrow){margin:0;color:rgba(255,255,255,.76);font:500 14px/1.5 var(--font-ui)}.showcase-video__actions{display:flex;gap:12px;margin-top:24px}.showcase-video__cta,.showcase-video__control{display:inline-flex;align-items:center;gap:8px;border-radius:999px;padding:11px 17px;font:700 13px/1 var(--font-ui);cursor:pointer;text-decoration:none}.showcase-video__cta{background:#e4b95b;color:#071523}.showcase-video__control{border:1px solid rgba(255,255,255,.32);background:rgba(255,255,255,.1);color:#fff}.showcase-video__meta{bottom:27px}.showcase-video__price{color:#fff;font:700 18px/1 var(--font-ui)}.showcase-video__score{color:#e4b95b}.showcase-video__progress{position:absolute;right:28px;bottom:0;left:28px;height:3px;background:rgba(255,255,255,.18)}.showcase-video__progress span{display:block;height:100%;background:#e4b95b}.showcase-video__dots{display:flex;justify-content:center;gap:8px;padding:16px;background:#071523}.showcase-video__dots button{width:30px;height:4px;border:0;border-radius:8px;padding:0;background:rgba(255,255,255,.2);cursor:pointer}.showcase-video__dots button.is-active{background:#e4b95b}@media(max-width:640px){.showcase-video__media{min-height:520px}.showcase-video__copy{left:24px;right:24px;bottom:92px}.showcase-video__topline,.showcase-video__meta{left:24px;right:24px}.showcase-video__actions{flex-wrap:wrap}}
"}</style></section>;
}
