export interface CompoundHeatmapMetric {
  id: string;
  name: string;
  nameAr: string;
  zone: string;
  zoneAr: string;
  avgPricePerSqm: number;
  rentalCapRate: number; // e.g. 11.4%
  fiveYearAppreciation: number; // e.g. 95%
  liquidityScore: number; // 1-10
  activeInventoryCount: number;
  avgRentalPriceMonthly: number;
  avgResalePrice: number;
  investmentTier: 'AAA' | 'AA' | 'A' | 'BBB';
  recommendation: 'Strong Buy' | 'High Rental Yield' | 'Capital Appreciation' | 'Balanced Core';
  badgeColor: string;
}

export const COMPOUNDS_HEATMAP_DATA: CompoundHeatmapMetric[] = [
  {
    id: 'mivida',
    name: 'Mivida (Emaar)',
    nameAr: 'ميفيدا — إعمار',
    zone: 'Golden Square',
    zoneAr: 'المربع الذهبي',
    avgPricePerSqm: 88500,
    rentalCapRate: 11.8,
    fiveYearAppreciation: 125,
    liquidityScore: 9.6,
    activeInventoryCount: 42,
    avgRentalPriceMonthly: 65000,
    avgResalePrice: 14500000,
    investmentTier: 'AAA',
    recommendation: 'Capital Appreciation',
    badgeColor: '#10b981',
  },
  {
    id: 'eastown',
    name: 'Eastown (SODIC)',
    nameAr: 'إيستاون — سوديك',
    zone: 'South 90th St',
    zoneAr: 'شارع التسعين الجنوبي',
    avgPricePerSqm: 72000,
    rentalCapRate: 13.4,
    fiveYearAppreciation: 110,
    liquidityScore: 9.8,
    activeInventoryCount: 58,
    avgRentalPriceMonthly: 48000,
    avgResalePrice: 10800000,
    investmentTier: 'AAA',
    recommendation: 'High Rental Yield',
    badgeColor: '#06b6d4',
  },
  {
    id: 'madinaty',
    name: 'Madinaty',
    nameAr: 'مدينتي',
    zone: 'Suez Road',
    zoneAr: 'طريق السويس',
    avgPricePerSqm: 42000,
    rentalCapRate: 14.2,
    fiveYearAppreciation: 90,
    liquidityScore: 9.9,
    activeInventoryCount: 380,
    avgRentalPriceMonthly: 32000,
    avgResalePrice: 5800000,
    investmentTier: 'AA',
    recommendation: 'High Rental Yield',
    badgeColor: '#3b82f6',
  },
  {
    id: 'palm-hills',
    name: 'Palm Hills New Cairo',
    nameAr: 'بالم هيلز التجمع',
    zone: 'Middle Ring Road',
    zoneAr: 'الدائري الأوسطي',
    avgPricePerSqm: 84000,
    rentalCapRate: 10.5,
    fiveYearAppreciation: 135,
    liquidityScore: 8.9,
    activeInventoryCount: 34,
    avgRentalPriceMonthly: 70000,
    avgResalePrice: 16200000,
    investmentTier: 'AAA',
    recommendation: 'Capital Appreciation',
    badgeColor: '#8b5cf6',
  },
  {
    id: 'hyde-park',
    name: 'Hyde Park',
    nameAr: 'هايد بارك',
    zone: 'South 90th St',
    zoneAr: 'شارع التسعين الجنوبي',
    avgPricePerSqm: 68000,
    rentalCapRate: 12.1,
    fiveYearAppreciation: 105,
    liquidityScore: 9.1,
    activeInventoryCount: 76,
    avgRentalPriceMonthly: 42000,
    avgResalePrice: 9400000,
    investmentTier: 'AA',
    recommendation: 'Balanced Core',
    badgeColor: '#f59e0b',
  },
  {
    id: 'villette',
    name: 'Villette (SODIC)',
    nameAr: 'فيليت — سوديك',
    zone: 'Golden Square',
    zoneAr: 'المربع الذهبي',
    avgPricePerSqm: 79000,
    rentalCapRate: 11.2,
    fiveYearAppreciation: 115,
    liquidityScore: 9.0,
    activeInventoryCount: 29,
    avgRentalPriceMonthly: 55000,
    avgResalePrice: 13200000,
    investmentTier: 'AAA',
    recommendation: 'Capital Appreciation',
    badgeColor: '#ec4899',
  },
  {
    id: 'swan-lake',
    name: 'Swan Lake Residences',
    nameAr: 'سوان ليك',
    zone: '1st Settlement',
    zoneAr: 'التجمع الأول',
    avgPricePerSqm: 115000,
    rentalCapRate: 9.8,
    fiveYearAppreciation: 145,
    liquidityScore: 9.4,
    activeInventoryCount: 18,
    avgRentalPriceMonthly: 95000,
    avgResalePrice: 24000000,
    investmentTier: 'AAA',
    recommendation: 'Strong Buy',
    badgeColor: '#10b981',
  },
  {
    id: 'mountain-view-icity',
    name: 'Mountain View iCity',
    nameAr: 'ماونتن فيو آي سيتي',
    zone: 'Northern Extension',
    zoneAr: 'التوسعات الشمالية',
    avgPricePerSqm: 56000,
    rentalCapRate: 13.8,
    fiveYearAppreciation: 120,
    liquidityScore: 9.3,
    activeInventoryCount: 112,
    avgRentalPriceMonthly: 38000,
    avgResalePrice: 7900000,
    investmentTier: 'AA',
    recommendation: 'High Rental Yield',
    badgeColor: '#06b6d4',
  },
  {
    id: 'waterway',
    name: 'The Waterway',
    nameAr: 'ذا ووتر واي',
    zone: 'North 90th St',
    zoneAr: 'شارع التسعين الشمالي',
    avgPricePerSqm: 105000,
    rentalCapRate: 12.8,
    fiveYearAppreciation: 130,
    liquidityScore: 9.7,
    activeInventoryCount: 14,
    avgRentalPriceMonthly: 85000,
    avgResalePrice: 19500000,
    investmentTier: 'AAA',
    recommendation: 'Strong Buy',
    badgeColor: '#10b981',
  },
  {
    id: 'al-rehab',
    name: 'Al Rehab City',
    nameAr: 'مدينة الرحاب',
    zone: 'Suez Road / 1st Sett.',
    zoneAr: 'طريق السويس / التجمع الأول',
    avgPricePerSqm: 49000,
    rentalCapRate: 14.5,
    fiveYearAppreciation: 85,
    liquidityScore: 9.9,
    activeInventoryCount: 240,
    avgRentalPriceMonthly: 28000,
    avgResalePrice: 5200000,
    investmentTier: 'AA',
    recommendation: 'High Rental Yield',
    badgeColor: '#3b82f6',
  },
];
