/**
 * Sierra Estates — client portal bilingual copy.
 * Ported verbatim from ui_kits/houzez-portal/shared.js I18N (EN source of truth;
 * AR is a genuine translation, warm/personal tone per brand voice).
 */
export type CopyKey = keyof typeof EN;

export const EN = {
  brandSub: 'Future of Real Estate',
  navHome: 'Home', navProps: 'Properties', navInv: 'Inventory', navCpds: 'Compounds', navExplore: '3D Explorer', navAgents: 'Agents', navContact: 'Contact', navAI: 'AI Tools',
  addListing: 'Add Listing', signIn: 'Sign In', langBtn: 'العربية',
  addr: 'Banafseg 2, Villa 402, New Cairo',
  heroSub: '21 compounds · 1,200+ units · AI-curated for you.',
  heroExplore: 'Explore in 3D',
  q1: '1,240+ verified listings', q2: '19 compounds', q3: 'RERA-licensed brokers',
  tabBuy: 'Resale', tabRent: 'Rent', tabNew: 'New Projects',
  fLoc: 'Location', fType: 'Property Type', fBeds: 'Bedrooms', fPrice: 'Max Price', search: 'Search',
  vLoc: 'New Cairo, Egypt', vType: 'Villa', vBeds: '4+ Beds', vPrice: 'EGP 25M',
  eyeList: 'AI-curated inventory', featTit: 'Featured Properties',
  featSub: 'The most sought-after homes on the market this week across New Cairo.', viewAll: 'View all listings',
  eyeCpd: 'Explore by area', cpdTit: 'Browse New Cairo Compounds',
  cpdSub: 'From gated family communities to waterfront lifestyle districts.', allCpds: 'All 29 compounds',
  eyeTour: 'Immersive 360° tour', tourTit: 'Tour a signature luxury villa in 360°', tourSub: 'Walk through our flagship New Cairo villa — drag to look around every room.',
  stat1: 'Active Listings', stat2: 'Compounds Covered', stat3: 'Licensed Agents', stat4: 'Closed in 2025',
  eyeWhy: 'Our advantage · AI-powered', whyTit: 'Why Sierra Estates',
  whySub: 'Every listing is verified, priced against live market data, and shown by a broker who knows the compound.',
  w1t: 'AI Opportunity Scanner', w1s: 'Sierra scans 1,200+ units daily using 6 AI tools — ROI, AVM pricing, smart matching — to surface best deals first.',
  w2t: 'Precise AVM Pricing', w2s: 'Real-time valuation engine benchmarks every unit against 25 compounds. No overpaying.',
  w3t: 'Human + AI Closing', w3s: 'AI-sourced opportunities paired with expert advisors. First match to signed contract in 48h.',
  w4t: 'Verified Inventory', w4s: 'Every listing personally verified on-site before appearing in your feed.',
  ctaTit: 'Have a property in New Cairo to sell or rent?', ctaSub: 'List with Sierra Estates and reach 40,000+ qualified buyers every month.',
  ctaBtn1: 'List your property', ctaBtn2: 'Talk to an agent',
  footBlurb: "Curated luxury rentals and resale across New Cairo’s premier compounds. Verified listings, licensed brokers, real market data.",
  footNews: 'Get new listings by email',
  fExplore: 'Explore', fBuy: 'Buy a home', fRent: 'Rent a home', fNew: 'New projects', fCpds: 'Compounds', fAgent: 'Find an agent',
  fCompany: 'Company', fAbout: 'About Sierra', fBrokers: 'Our brokers', fJournal: 'Journal', fCareers: 'Careers', fContact: 'Contact',
  fTouch: 'Get in touch', fAddr: 'Banafseg 2, Villa 402, New Cairo, Egypt',
  rights: '© 2026 Sierra Estates. All rights reserved.',
  crumbHome: 'Home',
  propsTit: 'Properties', propsSub: 'AI-curated rent & resale inventory across New Cairo — every unit verified on-site.',
  cpdsTit: 'Compound Intelligence', cpdsSub: 'New Cairo · Live — 29 compounds benchmarked by AI score, growth and price.',
  searchCpdPh: 'Search by compound name…', browseMap: 'Browse map', noCpd: 'No compounds match your filters.',
  filterAll: 'All', filterVilla: 'Villas', filterApt: 'Apartments', filterTown: 'Townhouses & Twins', filterPent: 'Penthouses & Duplex',
  modeAll: 'All', modeSale: 'Resale', modeRent: 'Rent',
  results: 'results',
  beds: 'Beds', baths: 'Baths', avg: 'Avg. villa', growth: 'YoY growth', aiScore: 'AI Score', rentAvg: 'Rent avg.',
  backProps: 'Back to properties', schedule: 'Schedule a viewing', wa: 'WhatsApp', call: 'Call Agent',
  overview: 'Overview', location: 'Location', similar: 'Similar homes', advisor: 'Listing Advisor', amenities: 'Amenities',
  z1: '5th Settlement', z2: 'Katameya', z3: 'New Cairo Core', z4: 'Mostakbal City',
  eyeTesti: 'Client stories', testiTit: 'What our clients say', testiSub: 'Real moves, closed by Sierra advisors.',
  t1q: "Sierra’s AI match found our Hyde Park villa in two days — after three months of searching everywhere else.", t1n: 'Ahmed & Dina El-Shazly', t1r: 'Bought in Hyde Park',
  t2q: 'The AVM pricing report saved us from overpaying by EGP 2M. Data first, pressure never.', t2n: 'Mohamed Ezz', t2r: 'Bought in Mivida',
  t3q: 'Listed on Monday, three qualified viewings by Thursday, signed within the week.', t3n: 'Sara Mansour', t3r: 'Rented out in Eastown',
  eyePerfect: 'Why choose us', perfTit: 'Sierra is the perfect choice', perfSub: "Three reasons New Cairo’s smartest buyers start here.",
  pc1t: 'Largest verified inventory', pc1s: '1,240+ rent & resale units across 29 compounds — every one walked and photographed by our team.',
  pc2t: 'Data you can act on', pc2s: 'Live AVM valuations, growth benchmarks and AI scores on every unit — not broker guesswork.',
  pc3t: 'Advisors, not salespeople', pc3s: 'RERA-licensed compound specialists paid on your satisfaction, not just the close.',
  inqTit: 'Real-estate inquiry', inqSub: 'Tell us what you need — an advisor replies within 2 hours.',
  inqBuy: 'Buy', inqRent: 'Rent', inqSell: 'Sell',
  inqName: 'Full name', inqEmail: 'Email', inqPhone: 'Phone', inqZone: 'Preferred zone', inqType2: 'Property type', inqBudget: 'Budget (EGP)', inqMsg: 'Message (optional)', inqSend: 'Send inquiry',
  inqSending: 'Sending…', inqOk: 'Thank you — an advisor will reach out within 2 hours.', inqErr: 'Something went wrong. Please try again or WhatsApp us.',
  inqNameReq: 'Please enter your name.',
  partEye: 'Trusted developer partners',
  fDiscover: 'Discover',
  aiEye: 'AI · 7 tools online', aiTit: 'First AI real-estate ecosystem in the Middle East', aiSub: 'Live AI tools for every step of your property journey.',
  ai1t: 'AI Engine 3.0', ai1s: 'Real-time AVM pricing, ROI signals & Q2 2026 market data.',
  ai2t: 'Smart Match', ai2s: 'AI pairs your criteria to the perfect listing.',
  ai3t: 'ROI Analysis', ai3s: 'Yield leaderboard, cap rate & cashflow.',
  ai4t: 'Precise Pricing', ai4s: 'AVM-calibrated fair-market price range.',
  ai5t: 'Dream Home Finder', ai5s: '4 questions → your compound match.',
  ai6t: 'Intelligence Map', ai6s: 'Live compound map — explore units by area.',
  ai7t: 'Virtual Tour', ai7s: '360° immersive walkthrough of top units.',
  aiLive: 'Live',
  lVilla: 'Villas', lApt: 'Apartments', lTwin: 'Twin & Townhouses', lPent: 'Penthouses & Duplexes', listingsWord: 'listings',
  unitsWord: 'units', unitsTit: 'Available units',
  chatTitle: 'Sierra', chatStatus: 'AI concierge · online', chatPlaceholder: 'Ask about listings, prices, viewings…',
  chatGreeting: "Hi, I'm Sierra — your AI concierge. Tell me what you're looking for in New Cairo and I'll find your match.",
  tourNote: 'Full 360° three.js virtual tour coming soon.',
} as const;

export const AR: Record<CopyKey, string> = {
  brandSub: 'مستقبل العقارات',
  navHome: 'الرئيسية', navProps: 'العقارات', navInv: 'المخزون', navCpds: 'الكمبوندات', navExplore: 'المستكشف ثلاثي الأبعاد', navAgents: 'المستشارون', navContact: 'تواصل', navAI: 'أدوات الذكاء',
  addListing: 'أضف عقارك', signIn: 'دخول', langBtn: 'English',
  addr: 'البنفسج 2، فيلا 402، القاهرة الجديدة',
  heroSub: '21 كمبوند · +1200 وحدة · منتقاة لك بالذكاء الاصطناعي.',
  heroExplore: 'استكشف ثلاثي الأبعاد',
  q1: '+1240 عقار موثّق', q2: '19 كمبوند', q3: 'وسطاء مرخّصون',
  tabBuy: 'بيع', tabRent: 'إيجار', tabNew: 'مشروعات جديدة',
  fLoc: 'الموقع', fType: 'نوع العقار', fBeds: 'الغرف', fPrice: 'أقصى سعر', search: 'ابحث',
  vLoc: 'القاهرة الجديدة، مصر', vType: 'فيلا', vBeds: '+4 غرف', vPrice: '25 مليون جنيه',
  eyeList: 'مخزون منتقى بالذكاء', featTit: 'عقارات مميزة',
  featSub: 'أكثر المنازل طلباً هذا الأسبوع في القاهرة الجديدة.', viewAll: 'عرض كل العقارات',
  eyeCpd: 'استكشف حسب المنطقة', cpdTit: 'تصفح كمبوندات القاهرة الجديدة',
  cpdSub: 'من مجتمعات عائلية مغلقة إلى أحياء حياة عصرية.', allCpds: 'كل الكمبوندات (29)',
  eyeTour: 'جولة 360° غامرة', tourTit: 'جولة 360° داخل فيلا فاخرة', tourSub: 'تجوّل داخل فيلا القاهرة الجديدة — اسحب لتستكشف كل غرفة.',
  stat1: 'عقار نشط', stat2: 'كمبوند', stat3: 'مستشار مرخّص', stat4: 'مبيعات 2025',
  eyeWhy: 'مزايانا · بالذكاء الاصطناعي', whyTit: 'لماذا سيرا إستيتس',
  whySub: 'كل عقار موثّق، مسعّر ببيانات السوق الحية، ويعرضه مستشار يعرف الكمبوند جيداً.',
  w1t: 'ماسح الفرص الذكي', w1s: 'سيرا يفحص +1200 وحدة يومياً بـ 6 أدوات ذكاء اصطناعي لإيجاد أفضل الفرص أولاً.',
  w2t: 'تسعير AVM دقيق', w2s: 'محرك تقييم فوري يقارن كل وحدة مع 25 كمبوند في الوقت الفعلي.',
  w3t: 'إغلاق بشري + ذكاء', w3s: 'فرص يكتشفها الذكاء الاصطناعي مع مستشارين خبراء. من التوافق حتى التوقيع خلال 48 ساعة.',
  w4t: 'مخزون موثّق', w4s: 'كل عقار يُعاين ميدانياً قبل ظهوره أمامك.',
  ctaTit: 'لديك عقار في القاهرة الجديدة للبيع أو الإيجار؟', ctaSub: 'اعرضه مع سيرا إستيتس وصِل إلى +40 ألف مشترٍ جاد شهرياً.',
  ctaBtn1: 'اعرض عقارك', ctaBtn2: 'تحدّث مع مستشار',
  footBlurb: 'إيجار وبيع فاخر منتقى في أرقى كمبوندات القاهرة الجديدة. عقارات موثّقة، وسطاء مرخّصون، بيانات سوق حقيقية.',
  footNews: 'استقبل العقارات الجديدة بالبريد',
  fExplore: 'استكشف', fBuy: 'اشترِ منزلاً', fRent: 'استأجر منزلاً', fNew: 'مشروعات جديدة', fCpds: 'الكمبوندات', fAgent: 'ابحث عن مستشار',
  fCompany: 'الشركة', fAbout: 'عن سيرا', fBrokers: 'مستشارونا', fJournal: 'المدونة', fCareers: 'وظائف', fContact: 'تواصل',
  fTouch: 'تواصل معنا', fAddr: 'البنفسج 2، فيلا 402، القاهرة الجديدة، مصر',
  rights: '© 2026 سيرا إستيتس. جميع الحقوق محفوظة.',
  crumbHome: 'الرئيسية',
  propsTit: 'العقارات', propsSub: 'مخزون إيجار وبيع منتقى بالذكاء الاصطناعي في القاهرة الجديدة — كل وحدة موثّقة ميدانياً.',
  cpdsTit: 'ذكاء الكمبوندات', cpdsSub: 'القاهرة الجديدة · مباشر — 29 كمبوند مقيّمة بالذكاء الاصطناعي والنمو والسعر.',
  searchCpdPh: 'ابحث باسم الكمبوند…', browseMap: 'تصفح الخريطة', noCpd: 'لا توجد كمبوندات مطابقة.',
  filterAll: 'الكل', filterVilla: 'فيلات', filterApt: 'شقق', filterTown: 'تاون هاوس وتوين', filterPent: 'بنتهاوس ودوبلكس',
  modeAll: 'الكل', modeSale: 'بيع', modeRent: 'إيجار',
  results: 'نتيجة',
  beds: 'غرف', baths: 'حمامات', avg: 'متوسط الفيلا', growth: 'نمو سنوي', aiScore: 'تقييم الذكاء', rentAvg: 'متوسط الإيجار',
  backProps: 'عودة إلى العقارات', schedule: 'احجز معاينة', wa: 'واتساب', call: 'اتصل بالمستشار',
  overview: 'نظرة عامة', location: 'الموقع', similar: 'منازل مشابهة', advisor: 'مستشار العقار', amenities: 'المميزات',
  z1: 'التجمع الخامس', z2: 'القطامية', z3: 'قلب القاهرة الجديدة', z4: 'مدينة المستقبل',
  eyeTesti: 'قصص عملائنا', testiTit: 'ماذا يقول عملاؤنا', testiSub: 'صفقات حقيقية أغلقها مستشارو سيرا.',
  t1q: 'توافق سيرا الذكي وجد فيلتنا في هايد بارك خلال يومين — بعد ثلاثة أشهر من البحث في كل مكان.', t1n: 'أحمد ودينا الشاذلي', t1r: 'شراء في هايد بارك',
  t2q: 'تقرير التسعير AVM وفّر علينا مليوني جنيه. بيانات أولاً، ولا ضغوط إطلاقاً.', t2n: 'محمد عز', t2r: 'شراء في ميفيدا',
  t3q: 'عرضنا الوحدة الإثنين، ثلاث معاينات جادة الخميس، ووقّعنا خلال أسبوع.', t3n: 'سارة منصور', t3r: 'تأجير في إيستاون',
  eyePerfect: 'لماذا نحن', perfTit: 'سيرا هي الاختيار الأمثل', perfSub: 'ثلاثة أسباب تجعل أذكى المشترين يبدأون من هنا.',
  pc1t: 'أكبر مخزون موثّق', pc1s: '+1240 وحدة إيجار وبيع في 29 كمبوند — كل وحدة عوينت وصوّرت ميدانياً.',
  pc2t: 'بيانات قابلة للتنفيذ', pc2s: 'تقييمات AVM حية ومؤشرات نمو وتقييم ذكاء لكل وحدة — لا تخمينات وسطاء.',
  pc3t: 'مستشارون لا بائعون', pc3s: 'متخصصو كمبوندات مرخّصون يُقيّمون برضاك، لا بالإغلاق فقط.',
  inqTit: 'طلب عقاري', inqSub: 'أخبرنا بما تحتاج — يرد مستشار خلال ساعتين.',
  inqBuy: 'شراء', inqRent: 'إيجار', inqSell: 'بيع',
  inqName: 'الاسم بالكامل', inqEmail: 'البريد الإلكتروني', inqPhone: 'الهاتف', inqZone: 'المنطقة المفضلة', inqType2: 'نوع العقار', inqBudget: 'الميزانية (جنيه)', inqMsg: 'رسالة (اختياري)', inqSend: 'أرسل الطلب',
  inqSending: 'جارٍ الإرسال…', inqOk: 'شكراً لك — سيتواصل معك مستشار خلال ساعتين.', inqErr: 'حدث خطأ ما. حاول مجدداً أو راسلنا على واتساب.',
  inqNameReq: 'من فضلك أدخل اسمك.',
  partEye: 'شركاء التطوير الموثوقون',
  fDiscover: 'اكتشف',
  aiEye: 'ذكاء اصطناعي · 7 أدوات تعمل', aiTit: 'أول نظام ذكاء عقاري في الشرق الأوسط', aiSub: 'أدوات ذكاء اصطناعي حية لكل خطوة في رحلتك العقارية.',
  ai1t: 'محرك الذكاء 3.0', ai1s: 'تسعير AVM لحظي، مؤشرات عائد، وبيانات سوق 2026.',
  ai2t: 'التوافق الذكي', ai2s: 'يطابق الذكاء معاييرك مع العقار المثالي.',
  ai3t: 'تحليل العائد', ai3s: 'قوائم العائد ومعدل الربح والتدفق النقدي.',
  ai4t: 'تسعير دقيق', ai4s: 'نطاق سعر عادل معاير بـ AVM.',
  ai5t: 'مستشار منزل الأحلام', ai5s: '4 أسئلة ← الكمبوند المثالي لك.',
  ai6t: 'خريطة الذكاء', ai6s: 'خريطة كمبوندات حية — استكشف الوحدات حسب المنطقة.',
  ai7t: 'جولة افتراضية', ai7s: 'جولة 360° غامرة في أفضل الوحدات.',
  aiLive: 'مباشر',
  lVilla: 'فيلات', lApt: 'شقق', lTwin: 'توين وتاون هاوس', lPent: 'بنتهاوس ودوبلكس', listingsWord: 'عقار',
  unitsWord: 'وحدة', unitsTit: 'الوحدات المتاحة',
  chatTitle: 'سيرا', chatStatus: 'مساعد ذكي · متصل', chatPlaceholder: 'اسأل عن العقارات والأسعار والمعاينات…',
  chatGreeting: 'أهلاً، أنا سيرا — مساعدك الذكي. قل لي عمّا تبحث في القاهرة الجديدة وسأجد لك الأنسب.',
  tourNote: 'الجولة الافتراضية 360° بتقنية three.js قريباً.',
};

export function makeT(locale: 'en' | 'ar') {
  const dict = locale === 'ar' ? AR : EN;
  return (k: CopyKey): string => dict[k] ?? EN[k] ?? String(k);
}
